[package]
name = "sha2-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm = { workspace = true }
sha2 = { version = "0.10.8", default-features = false }

[features]
default = []
std = ["openvm/std"]
