[package]
name = "ecadd"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[[target.executable]]

[dependencies]
garaga = { git = "https://github.com/varunthakore/garaga.git", branch = "fix-serde" }
cairo_run = ">=2.9.2"
cairo_execute = "2.9.2"