[workspace]
[package]
version = "0.1.0"
name = "bigmem"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", rev = "4551cd6daf9428db36b5fabc3f46acb379ba9e22" }
