[package]
name = "ec"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html
#
# scarb buid - works
#
# scarb prove --execute --print-program-output --arguments 2
# Error: 
# thread 'main' panicked at /cargo/git/checkouts/stwo-cairo-ef02e8e85a2fe399/c0f36e2/stwo_cairo_prover/crates/prover/src/components/range_check_builtin_bits_128/prover.rs:16:9:
# assertion failed: log_size >= LOG_N_LANES
# note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#
# root@ubuntu-32gb-hel1-1:~/zkvm-benchmarks/stwo/ec# scarb --version
# scarb 2.10.1 (ea6b66386 2025-02-20)
# cairo: 2.10.1 (https://crates.io/crates/cairo-lang-compiler/2.10.1)
# sierra: 1.7.0

[[target.executable]]

[cairo]
enable-gas = false

[dependencies]
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git" }
cairo_execute = "2.9.2"

[dev-dependencies]
cairo_test = "2.9.2"