[package]
name = "sha3-chain-guest"
version = "0.1.0"
edition = "2021"

[features]
guest = []

[dependencies]
jolt = { package = "jolt-sdk", git = "https://github.com/a16z/jolt" }
sha3 = { version = "0.10.8", default-features = false }
