[package]
name = "sha3"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/openvm-org/openvm.git", default-features = false }
sha3 = { version = "0.10.8", default-features = false }

[features]
default = []
std = ["openvm/std"]
