[package]
name = "fib"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/openvm-org/openvm.git", default-features = false }

[features]
default = []
std = ["openvm/std"]
