[package]
name = "sha2-precompile"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm = { workspace = true }
openvm-sha2 = { git = "https://github.com/openvm-org/openvm.git" }

[features]
default = []
std = ["openvm/std"]