[package]
name = "sha2-chain-precompile"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm = { git = "https://github.com/openvm-org/openvm.git" }
openvm-sha256-guest = { git = "https://github.com/openvm-org/openvm.git" }

[features]
default = []
std = ["openvm/std"]
