[package]
name = "ec"
version = "0.1.0"
edition = "2021"

[dependencies]
openvm = { workspace = true }
ark-secp256k1 = { version = "0.5.0", default-features = false }

[features]
default = []
std = ["openvm/std"]