[workspace]
[package]
version = "0.1.0"
name = "sha2-chain"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", rev = "4551cd6daf9428db36b5fabc3f46acb379ba9e22" }
sha3 = { version = "0.10.8", default-features = false }
