name: "Benchmark Blake"

on:
  push:
    branches:
      - stwo-blake
    paths-ignore:
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-bench
  cancel-in-progress: true

jobs:
  create-runner:
    name: Create Hetzner Cloud Runner
    runs-on: ubuntu-24.04
    outputs:
      label: ${{ steps.create-hcloud-runner.outputs.label }}
      server_id: ${{ steps.create-hcloud-runner.outputs.server_id }}
    steps:
      - name: Create Runner
        id: create-hcloud-runner
        uses: Cyclenerd/hcloud-github-runner@v1
        with:
          name: gh-benchmark-runner
          mode: create
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          # ccx13: dedicated CPU,  2 cores,   8 GB RAM
          # ccx53: dedicated CPU, 32 cores, 128 GB RAM
          # ccx63: dedicated CPU, 48 cores, 192 GB RAM
          server_type: ccx63
          location: fsn1
          ssh_key: 27148616
          image: ubuntu-24.04

  benchmark:
    name: Execute on the Benchmarking Machine
    timeout-minutes: 1440 # 24 hrs
    needs: create-runner
    runs-on: ${{ needs.create-runner.outputs.label }}
    env:
      BENCH_USER: shodan
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Benchmark User
        run: |
          sudo useradd -m -s /bin/bash $BENCH_USER
          sudo usermod -aG sudo $BENCH_USER
          echo "$BENCH_USER ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/$BENCH_USER
          sudo chown -R $BENCH_USER:$BENCH_USER .

      - name: Setup Benchmark Dependencies
        run: |
          sudo -u $BENCH_USER ./setup.sh

      - name: Run Benchmark
        run: |
          WORK_DIR=$(pwd)
          echo "${{ secrets.SHARP_CLIENT_CERT }}" > user-cert.pem
          echo "${{ secrets.SHARP_CLIENT_KEY }}" > user-key.pem
          chmod 644 user-cert.pem user-key.pem
          sudo -u $BENCH_USER \
            SHARP_CLIENT_CERT="$WORK_DIR/user-cert.pem" \
            SHARP_KEY_PATH="$WORK_DIR/user-key.pem" \
            SHARP_KEY_PASSWD="${{ secrets.SHARP_CLIENT_KEY_PASSWORD }}" \
            bash -c "cd $WORK_DIR && ./bench.sh . \"4096 8192 16384 32768 65536 131072 262144 524288\" \"256 512 1024 2048 4096 8192 16384\" \"8 16 32 64 128 256 512 1024 2048 4096\" \"4 8 16 32 64\" \"16 32 64 128 256 512 1024 2048\""
        # fib_args sha_args sha_chain_args matmul_args ec_args

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: |
            *.txt
            *.log
            ./benchmark_outputs/*.csv
            ./report_info/*.txt
            *.csv
            *.json
            *.data
            *.png
            *.jpg
            *.svg

  delete-runner:
    name: Delete Hetzner Cloud Runner
    needs:
      - create-runner
      - benchmark
    runs-on: ubuntu-24.04
    if: ${{ always() }}
    steps:
      - name: Delete runner
        uses: Cyclenerd/hcloud-github-runner@v1
        with:
          mode: delete
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
          name: ${{ needs.create-runner.outputs.label }}
          server_id: ${{ needs.create-runner.outputs.server_id }}
