name: "Benchmark Setup"

on:
  push:
    branches-ignore:
      - main
      - master
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  benchmark:
    name: Setup Benchmark
    runs-on: ubuntu-latest
    env:
      BENCH_USER: shodan
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Create Benchmark User
        run: |
          sudo useradd -m -s /bin/bash $BENCH_USER
          sudo usermod -aG sudo $BENCH_USER
          echo "$BENCH_USER ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/$BENCH_USER
          sudo chown -R $BENCH_USER:$BENCH_USER .

      - name: Setup Benchmark Dependencies
        run: |
          echo "${{ secrets.SHARP_CLIENT_CERT }}" > user-cert.pem
          echo "${{ secrets.SHARP_CLIENT_KEY }}" > user-key.pem
          sudo -u $BENCH_USER \
            SHARP_CLIENT_CERT=./user-cert.pem \
            SHARP_KEY_PATH=./user-key.pem \
            SHARP_KEY_PASSWD=${{ secrets.SHARP_CLIENT_KEY_PASSWORD }} \
            ./setup.sh
