name: "Benchmark Setup"

on:
  push:
    branches-ignore:
      - main
      - master
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  benchmark:
    name: Setup Benchmark
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Benchmark Dependencies
        run: |
          echo "${{ secrets.SHARP_CLIENT_CERT }}" > user-cert.pem
          echo "${{ secrets.SHARP_CLIENT_KEY }}" > user-key.pem
          sudo -u $BENCH_USER \
            SHARP_KEY_PATH=./user-key.pem \
            SHARP_API_CERT=./user-cert.pem \
            SHARP_KEY_PASSWD=${{ secrets.SHARP_API_KEY_PASSWORD }} \
            ./setup.sh
